### ISSUE TITLE
Temporary panel

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WalCommander#213]
To store found files, etc.

**Comment by corporateshark** [comment]
How about following up and adding a "file system" for #207?

**Comment by corporateshark** [comment]
#11 is also very close.

**Comment by helgp** [comment]
This sounds reasonable - after finishing the temp panel.

**Comment by helgp** [comment]
Currently it is stable, and has all the features that I have initially planned. I am stopping the глюкалополировательные activities on the subject. Feature requests and bug reports are welcome.
