### ISSUE TITLE
Change fonts

### ISSUE THREAD

**Issue by abishai** [corporateshark/WalCommander#281]
I can't change fonts for Viewer, Editor and Terminal. Is there special requirements for these fonts ? Both Set Fonts and Set X11 Fonts are empty for these controls

**Comment by abishai** [comment]
If it matters I run http://www.freshports.org/x11-fm/walcommander/ port with TrueType option set

**Comment by corporateshark** [comment]
Can you so solve this locally by editing ```~/.wcm/config```?

**Comment by abishai** [comment]
Yes. Thank you for the suggestion.
