### ISSUE TITLE
add feature folders history?

### ISSUE THREAD

**Issue by dizzy1984** [corporateshark/WalCommander#297]

**Comment by viktor-podzigun** [comment]
+1

Any one on this? I could try to create pull-request for this feature. Really missing it.

**Comment by corporateshark** [comment]
@viktor-podzigun: if you can implement it, just go ahead! That would be great!

**Comment by viktor-podzigun** [comment]
I've started working on it. And have small technical question.

User changes directories very quickly. Should we update (persist) config settings (registry) for folder history on each change, or just once before application exit?

**Comment by helgp** [comment]
I would vote for the approach to manage it with all other configuration settings: i.e. persist on exit, if autosave config is on, and on demand with options-Save Setup.  

See the use of clConfigReader/clConfigWriter for OS-independent API.

**Comment by corporateshark** [comment]
Only on exit. Use LRU policy to update directories and store only reasonable fixed number of entries.

**Comment by viktor-podzigun** [comment]
Thanks for clarifications. Will persist folder history config on exit and limit it to 50 items.

One more. I guess that Virtual File System folders like (S)FTP should also work, similar to current Folder shortcuts?

**Comment by corporateshark** [comment]
@viktor-podzigun yes, indeed.

**Comment by viktor-podzigun** [comment]
Created PR: https://github.com/corporateshark/WalCommander/pull/353

**Comment by viktor-podzigun** [comment]
@corporateshark how do you think, what the next useful feature/improvement I can help with? Maybe viewer history? :)

BTW: Is there any discussion forum/group for devs?

**Comment by singalen** [comment]
@viktor-podzigun Speaking of histories - may I ask for history in dialog fields?..
https://groups.google.com/forum/#!forum/wal-commander

**Comment by corporateshark** [comment]
https://github.com/corporateshark/WalCommander/issues/80

**Comment by corporateshark** [comment]
@viktor-podzigun #80 was already implemented in the original Wal Commander 0.17.2. Can you tackle it and merge into our fork?

**Comment by viktor-podzigun** [comment]
Sure, will take a look. Where I can find sources of Wal Commander 0.17.2 ?

**Comment by corporateshark** [comment]
https://github.com/corporateshark/WalCommander/tree/wcm-upstream
