### ISSUE TITLE
add feature "view history"?

### ISSUE THREAD

**Issue by dizzy1984** [corporateshark/WalCommander#298]

**Comment by viktor-podzigun** [comment]
Some technical details about implementation of this feature:

Current EditorPositions, and ViewerPositions configs will be removed and combined together into one ViewHistory config.

Do we need to jump to (open) the folder of the selected view/edit file in the current panel and select the file, also? So, when the user will close viewer/editor he will see the file under cursor. I think it will be nice feature. What do you think?

**Comment by corporateshark** [comment]
Should be configurable, since FAR does not do this.

**Comment by viktor-podzigun** [comment]
Agree. Then this can be added later.

**Comment by viktor-podzigun** [comment]
Implemented in https://github.com/corporateshark/WalCommander/commit/26ff3f3664a3e4aff2d1c77f93d04f9cbacf43cb
