### ISSUE TITLE
"-" instead of space when creating new directory

### ISSUE THREAD

**Issue by dizzy1984** [corporateshark/WalCommander#305]
Maybe this is not an issue - some misunderstanding - but even with panel settings->show spaces as "-" in names set to "no", i can see "-" when i type space in F7 dialog.
But when i copying this "-" i get " ".
I tried few different fonts and still i see "-"

**Comment by corporateshark** [comment]
The purpose of this feature is to make trailing spaces in the file names easily detectable. There may be a problem with some fonts, however, the same feature is implemented in the recent versions of FAR.

**Comment by corporateshark** [comment]
This is only a visual feature, the actual name should contain space and not this special symbol.
