### ISSUE TITLE
pure CMake build: "make install" won't install shared files

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#308]
I've built wcm with cmake and did `sudo make install`. `/usr/share/wcm/...` files were not installed. Moreover, they should go to `/usr/local/share/`. After copying them to `/usr/local/share/`by hand, they still were not picked up (wcm looked in `/usr/share/` instead).

**Comment by AMDmi3** [comment]
@corporateshark, which share/ files should be installed and how are they used?

**Comment by corporateshark** [comment]
``install-files\share``

Take a look at ``makefile.linux``:
```
install: wcm
	$(INSTALL_DIR)	$(BIN_DIR)
	$(INSTALL_DIR)	$(TARGET_DIR)
	$(INSTALL_PROGRAM) wcm $(BIN_DIR)
	$(INSTALL_TREE) install-files/* $(TARGET_DIR)
```

**Comment by corporateshark** [comment]
@AMDmi3 can we fix this?

**Comment by AMDmi3** [comment]
It's in my queue. Be patient.
