### ISSUE TITLE
Second confirmation (red) "delete?" dialog lacks keyboard shortcuts

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#310]
In Far/mc, every option in delete/overwrite confirmation dialogs has a keyboard shortcut.
For instance, "All" has "L" shortcut in both (?).
It would be great to back error-prone Tab-Enter keyboard navigation with single-key shortcuts.

**Comment by singalen** [comment]
May I ask to reopen this one.

The shortcuts in dialog windows are actually 2 shortcuts each:
* One is Alt+Key that works in every control;
* One is just the Key, if the focus is not in a text input box (or the current control doesn't capture the key in other way).

This rids the user of the necessity to press Alt, and it's the way it works in Far an mc.
Even WAL Commander's shortcuts in its main menu are not Alt+Key (as Alt is used for a different purpose), but Key only.

**Comment by helgp** [comment]
Red dialogs in Far do not have hotkeys at all.
Mc is terminal application. It can not rely on 'Alt' key in critical "Red" dialogs.

Hotkeys in wcm are designed to match functionality of GUI app in Windows or X - both in menus and dialogs.

**Comment by singalen** [comment]
I don't like an extra key, but I agree.
