### ISSUE TITLE
Feature reduction request: are multiple fonts actually needed?

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#311]
This one is pretty subjective, though how many people are going to setup different fonts? Given that the program is supposed to maintain same window size.
I'd rather leave a single font in settings, or not bother and put a setting into config file.

**Comment by corporateshark** [comment]
Different fonts are good and it is a good feature to be able to change them separately. This is the advantage of a graphical UI.

**Comment by singalen** [comment]
Er, this is not EXACTLY the advantage of a GUI. Well, ok. 
Thanks for a great piece of a software :+1:

**Comment by corporateshark** [comment]
Current solution allows those who want to set up a single font for everything to do so. If we remove this customization feature, those who want different fonts will be thrown overboard.

**Comment by singalen** [comment]
I wonder if there are more than 2 people who actually use and care for more than 1 font.
It's normally not worth complicating the UI for all the other users. You know all this stuff that features need to be judged and their existence sufficiently justified: http://www.joelonsoftware.com/items/2006/11/21.html

**Comment by corporateshark** [comment]
That blog post is on features to be implemented. What we have here is the tested and shipped feature. Now removing it will be the actual work. So no, it will stay that way for some time.

**Comment by singalen** [comment]
`That blog post is on features to be implemented` - sorry, the whole body is about reduction of existing features. Plus, the objective criterion is a king: what percent of users needs this feature?
I'll be happy to submit a pull request when I have the time ;)

**Comment by corporateshark** [comment]
Ok
