### ISSUE TITLE
Feature request: Built-in editor - Ctrl-number bookmarks

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#312]
FAR's internal editor has a feature: RightCtrl-digit sets a bookmark (cursor and scroll position) and LeftCtrl-digit restores it.
Would love to have this one.

**Comment by singalen** [comment]
Doesn't work in Linux. I tried to quickly analyze it, but didn't manage to.
I only found that `EditWin::EventKey(cevent_key* pEvent)` always gets a `pEvent->ExtMod()` without a `EXT_KM_LCTRL` (and without RCTRL) bit. I'm stuck in `swl_wincoreUX.cpp`, `DoKeyEvent()`

**Comment by corporateshark** [comment]
Fixed for OS X. Should also work on Linux. Please, try.

**Comment by corporateshark** [comment]
70b92de57ebacdffe2e77a61ade8d27162c18e97

**Comment by singalen** [comment]
Perfect, thanks!
