### ISSUE TITLE
Feature request: Shift-Enter should open file/directory in a default file manager (Explorer/Files)

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#320]
Far works this way.
Sometimes the default maanager can do stuff that wcm or Far cannot.

**Comment by viktor-podzigun** [comment]
+1

And when typed '.' (dot) and then Shift+Enter the current directory opens in the default system file explorer.

**Comment by singalen** [comment]
@viktor-podzigun Shift-Enter on ".." in current directory does it for me in Far.
Probably Shift-Enter when there's something in command line in Far starts it like "start" command.

BTW I believe we can vote on issues by starring them.

**Comment by viktor-podzigun** [comment]
Agreed, "Shift-Enter when there's something in command line" is probably separate feature.

**Comment by corporateshark** [comment]
Shift-Enter was already implemented in WCM for non-empty command line.
