### ISSUE TITLE
Current path in shell prompt is underlined with a mysterious gray line

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#321]
Please see attachment.
I see no useful information in this gray line and no reason for it to exist - it just distracts me.
![wal-dir-underlined](https://cloud.githubusercontent.com/assets/151199/5956834/b200443e-a7ba-11e4-8083-bba697cb833e.png)

**Comment by corporateshark** [comment]
I always thought that one was a feature. I checked the code and now I understand it was a bug.
