### ISSUE TITLE
When moving/deleting file panel **lost current file position** and select ".."

### ISSUE THREAD

**Issue by belonesox** [corporateshark/WalCommander#322]
When moving/deleting file panel lost current file position and select ".."
After deleting/moving selected file, WAL must select nearest item, not parent directory.

Ужасно, когда после удаления или перемещения файла полностью теряется контекст — текущий выбранный элемент, вместо него программа выбирает элемент родительского каталога.

Работать (разгребать-удалять) с  большими каталогами с таким подходом невозможно.

Нужно переходить на последний неудаленный (или следующий) элемент, надо посмотреть, как именно ведет себя Православный FaR.

**Comment by corporateshark** [comment]
Dup #73

**Comment by helgp** [comment]
I am currently working on this. Unfortunalely, orthodox implementation (like in Far) requires adding bsearch-style API to panel file lists.

**Comment by corporateshark** [comment]
Can we add a search API based on just a simple integer file index (in the current sorting mode)?

**Comment by helgp** [comment]
Consider the use case. 

Directory has files 1, 2, 3, 4, and 5. Cusror is on 3. User select-moves|deletes 2, and 3, leaving 1,4,5. Restoring position based on index would put cursor on 5. The right way is to place it on 4. To find the 4, wcm has to find where to put entry 3, which was under cursor before deletion, into the new list using active sort order. 

This is the API that I am taking about.

**Comment by corporateshark** [comment]
Indeed. Far puts the cursor on the next existing file if the previously selected file is missing.

**Comment by helgp** [comment]
Note that in "unsorted" panel mode Far restores cursor location based on previous cursor index. In unsorted mode, there is no way to find the location, where previous node under cursor would be placed into the unsorted list.

**Comment by corporateshark** [comment]
One possible solution can be retaining the previous files list.
