### ISSUE TITLE
Feature request: make option to hide scrollbars

### ISSUE THREAD

**Issue by belonesox** [corporateshark/WalCommander#323]
Feature request: make option to hide scrollbars.

Эстетика двухпанельников — в минимализме четких текстовых сеток. 
Появляющиеся в больших каталогах скроллеры (дико выпадающие по стилю, в отличии от опциональных текстовых скроллеров нортонов и прочих) ужасно раздражают, и бесполезны при основных юзкейсах, когда используют клавиатуру. 

Прошу сделать их отключаемыми, в том же меню со стилями, где можно отключить тулбары и прочую ересь.

**Comment by corporateshark** [comment]
Options -> Panel settings -> Show scrollbar

Same as in FAR.

**Comment by belonesox** [comment]
Thank you!
Sorry за слепоту. Искал ведь...
