### ISSUE TITLE
minor bug (appeared in 18.0.1) - highlighted shortcuts in Ctrl-D path shortcut menu stopped working

### ISSUE THREAD

**Issue by andrewelkin** [corporateshark/WalCommander#336]
As the 18.0.1 has a few beautiful improvements (thank you guys!), it's clearly a new bug. You can see it:

Ctrl-D
press any of highlighted letters for any of the stored paths
nothing happens.

**Comment by helgp** [comment]
At this time hotkeys in wcm tries to follow Windows hotkey convention for Menu/Dialogs.

- If menu is active, both Alt- and plain hotkeys work. 
- For inactive menu wcm can not use Alt-hotkey, as it is taken by Alt-Search feature.
- For dialogs wcm uses only Alt-hotkey, like Windows does

The observer behavior in Ctrl-D dialog falls into above picture. Alt-hotkeys work there just fine.

This is the second report on missing plain, non-Alt hotkeys. See #310. I am considering to change hotkey behavior in dialogs to follow the reports.
