### ISSUE TITLE
small bug with command line

### ISSUE THREAD

**Issue by dizzy1984** [corporateshark/WalCommander#340]
version:0.18.0 nov7
what is wrong :  cant delete selected word with del from command line
steps to reproduce :
1.type "sudo apt-get install pm-hibernate"
2.type "sudo apt-get install pm", previous command history will appear
3. select "install"
4. press del
nothing happens.

**Comment by corporateshark** [comment]
0.19
master : 19b66662ce2e8f6f09632777643eca70f00f83da

Cannot reproduce. Both Del and Ctrl+Del work just fine.
