### ISSUE TITLE
Dup some of mc's behavior: Bind 0 at the start of the command line after Esc to Quit wcm

### ISSUE THREAD

**Issue by egphilippov** [corporateshark/WalCommander#381]
So that Esc 0 would work the same way as F10. Fingers often automatically press Esc 0. There could be an option to disable/enable such Esc Key sequences at the config GUIs.

**Comment by corporateshark** [comment]
No escape sequences will be supported since they are meaningless on other platforms.

**Comment by helgp** [comment]
Wal (@gixer) is adding text-only UI to wcm. I am curious to see whether escape keyboard sequences appear there.
