### ISSUE TITLE
Broken layout in folder size dialog

### ISSUE THREAD

**Issue by helgp** [corporateshark/WalCommander#385]
To reproduce:
- Point cursor to a folder
- Press F3
- Observe that the numbers are cut:
![wcm-broken-size-dlg-layout](https://cloud.githubusercontent.com/assets/8525021/6240916/3d19e034-b6e3-11e4-8ed2-21bb7f7bb83f.png)

The bug is introduced with the commit 1945e79 on Feb 4: "Merge branch 'master' into attribs"

**Comment by corporateshark** [comment]
Is it fixed?

**Comment by helgp** [comment]
No, it is not fixed.

The introducing commit is almost 1K lines. I have failed to find anything there that could give a clue.

**Comment by corporateshark** [comment]
Please, test.

**Comment by helgp** [comment]
Works perfect!
