### ISSUE TITLE
Do not discard editor undo history when saving a file

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#388]
One might wish to undo beyond the last save point.

**Comment by corporateshark** [comment]
Editor settings

**Comment by singalen** [comment]
Maybe let's not make this an option? What's the use of the option nowdays, when we have gigabytes of memory? (it's not a rhetoric question - I really see no point except of cluttering the UI)

**Comment by corporateshark** [comment]
Because it is a potential data loss. For example:

* type something
* F2 to save
* sleep on Ctrl+Z

**Comment by corporateshark** [comment]
And, of course, Far does not have it. So, this is the compatible default behavior.

**Comment by singalen** [comment]
1. That's a much less likely scenario than misdeleting something and pressing F2.
2. It's covered by "Redo" after waking up.
3. Far's editor DOES have "undo after save" - I just tested it. Far has no option for this functionality - like most of editors out there (just tested Notepad).

**Comment by corporateshark** [comment]
Ok, let's enable it by default, same way as in Far.

**Comment by singalen** [comment]
It's not even an option in recent Far: 
![image](https://cloud.githubusercontent.com/assets/151199/6431031/d76fc996-c02a-11e4-8d91-9a432f92bcf7.png)

**Comment by corporateshark** [comment]
I see, but let's make it an option for some time. We already have it in there.
