### ISSUE TITLE
Make Linux binaries for 0.19.0

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WalCommander#393]
For the ``release-0.19.0`` branch.

https://github.com/corporateshark/WalCommander/tree/release-0.19.0

**Comment by helgp** [comment]
http://divgrad.com/walcommander/wcm_0.19.0-1_amd64.deb
http://divgrad.com/walcommander/wcm_0.19.0-1_i386.deb
http://divgrad.com/walcommander/wcm-0.19.0-2.x86_64.rpm
http://divgrad.com/walcommander/wcm-0.19.0-2.i386.rpm
