### ISSUE TITLE
When a command is executed, reset "last command" index for Ctrl-E/Ctrl-X

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#400]
Now, if I pick a command with Ctrl-E *and execute it or even clear it with Esc*, next Ctrl-E enters the command before the last one.
After the command is changed or executed, the Ctrl-E command index should be reset to last one executed.

Another problem in the same function: After a Ctrl-E, Ctrl-X should rotate command list back. But only the second Ctrl-X enters the previous command.

**Comment by corporateshark** [comment]
@singalen can you confirm it is fixed now?

**Comment by singalen** [comment]
Index reset works, but I'm afraid one more change is needed: #410
