### ISSUE TITLE
Ctrl-Ins on a panel should copy all the selected file names to a clipboard

### ISSUE THREAD

**Issue by singalen** [corporateshark/WalCommander#401]
Now only first selected file name is copied.
Scenario:
* mark several directories
* Press Ctrl-Ins
* Press Shift-Ins

Expected: all the marked directory names are pasted into command line.
Actual: only first selected directory name is pasted.

**Comment by corporateshark** [comment]
Actually it does. Pasting multiline text into ``EditLine`` was the problem.
