### ISSUE TITLE
Autocomplete behavior

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WalCommander#415]
#414, #80 

**Do:**

- press F7
- type ``dir``
- press ENTER
- delete the folder ``dir``
- press F7
- start typing ``d``
- press ENTER

**Observe:**

- autocomplete fills in the value automatically
- the folder named ``dir`` will be created

**Should be:**

- drop-down combo box should be visible once the word(s) is matched
- the folder named ``d`` should be created

Currently, what you type in the edit box is not what you get after hitting ENTER. The should-be behavior does not interfere with typing and that is how it works in FAR. It should work exactly the same way in WCM. Refer to the command line autocomplete implementation.

**Comment by viktor-podzigun** [comment]
Thanks for clarifying this. Now it's much clear how it should works.

I wasn't using the latest Far for reference (I still using the classic 1.7 version). But you are right, we should use new auto-complete behavior, as you described. And google search works this way, also :)

I will re-write the logic and will use current command line auto-complete as a reference.

**Comment by corporateshark** [comment]
The point is not to interfere with what a user types in.

**Comment by viktor-podzigun** [comment]
Since #80 was merged and closed, could we close this bug as well?

**Comment by corporateshark** [comment]
Good job!

**Comment by viktor-podzigun** [comment]
Thanks!

**Comment by viktor-podzigun** [comment]
BTW, not sure if I've mentioned it, but I also think this is really nice project, with a good idea and nice developers behind it. So I very exited to contribute!

**Comment by corporateshark** [comment]
You are always welcome!
