### ISSUE TITLE
Опция компилятора -std=c++11

### ISSUE THREAD

**Issue by biaks** [corporateshark/WalCommander#417]
Насколько необходима эта опция? Много ли на нее завязано? Эта опция автоматически ограничивает использование walcommander, так как не все имеют возможность пользоваться последними версиями компиляторов. У меня на всех рабочих компьютерах стоит gcc 4.6.1 и перейти на gcc 4.7 (где появляется поддержка опции c++11) нет никакой возможности. Можно ли ограничиться уровнем c++0x ?

**Comment by corporateshark** [comment]
WCM is written using features and libraries of C++11. The decision was intentional and will stay that way. Please, update your software.

**Comment by biaks** [comment]
Я не могу "update your software", я же сразу написал об этом. Я пишу под ОС Роса, у которой в репозиториях нет компилятора gcc 4.7 и не будет. Проблемы с обновлениями там из-за проблем с сертификацией.
Хорошо, ответьте мне пожалуйста на пару вопросов:
1. Почему вы отвечаете мне на английском, если я пишу вам на русском?
2. Насколько сложно собрать этот проект на gcc 4.6 c флагом c++0x ? Насколько сильно проект сейчас зависит от флага c++11?

**Comment by corporateshark** [comment]
Our language here is English. Please, respect our rules.

**Comment by helgp** [comment]
http://www.wal-commander.org/ не требует с++11.
