### ISSUE TITLE
Cursor is invisible for long time in all edit lines

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WalCommander#420]
**Do:**

- press Alt-F7
- press Tab to switch between two edit lines

**Observe:**

- cursor is invisible for a view seconds, then it starts blinking

**Should be:**
- cursor starts blinking immediately

**Comment by corporateshark** [comment]
Possibly was introduced in https://github.com/corporateshark/WalCommander/pull/414

**Comment by viktor-podzigun** [comment]
Yes, it is appears to happen only in edit lines that supports history (combo-boxes).

Will investigate and try to fix it.
