### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by KonstantinKuklin** [corporateshark/WalCommander#5]
Hi, thx for the work, but what do you think about date, when we will have os x version?

**Comment by frantic** [comment]
Started playing with Cocoa implementation for the UI...

![screenshot 2015-01-23 23 25 10](https://cloud.githubusercontent.com/assets/192222/5886507/b24693e2-a357-11e4-8ff1-93f3251fb264.png)

**Comment by corporateshark** [comment]
Good job!

**Comment by corporateshark** [comment]
@frantic How is it going? You can share your experience here https://groups.google.com/forum/#!forum/wal-commander

**Comment by frantic** [comment]
@corporateshark - I didn't get too far yet, but it's definitely possible.

**Comment by frantic** [comment]
(looks like I can't post to discussion forum...)


I've started working on a the Max OS X port of WalCommander. Here is my strategy:

1. Force all files to be Objective-C++, `cmake -G Xcode`
2. Create OSX native NSViews and NSWindows inside wal::Win
3. Inject OSX app runloop into `AppRun()`
4. Trigger updates via OSX view drawing events
5. Add code to wal::GC to draw on OSX views and X11 views (I'm here now)
6. Handle events from OSX runloop
7. Kill X11-specific code
8. Add Mac OS X specific features (menu, preview, etc.)
9. Put the resulting code into swl_wincoreCocoa and add ability to build the experimental version.
10. ...
11. Profit!

I'm sure there are things I missed and maybe it's going to be harder. Note that currently I'm just messing around with swl_wincoreUX to keep both implementation running at the same time.

I don't have much time to work on it, but you can follow the progress here
https://github.com/frantic/WalCommander/commits/osx-experimental

![screenshot 2015-02-08 23 26 35](https://cloud.githubusercontent.com/assets/192222/6111669/883d60a4-b03f-11e4-8481-04c26545d6cc.png)

**Comment by corporateshark** [comment]
@frantic Looks very nice. You are approved in the discussion group.

**Comment by viktor-podzigun** [comment]
Just discovered how to fix clipboard (Ctrl-C), go to the XQuartz menu:

X11 -> Preferences... -> Input -> un-tick "Enable key equivalents under X11"
