### ISSUE TITLE
File attributes (Ctrl+A)

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WalCommander#52]

**Comment by singalen** [comment]
Is this considered to be complete without
* file owner/group,
* multi-file attributes (including grayed "do not change" checkboxes) 
* and a "recursive" checkbox if a directory is hit?

**Comment by corporateshark** [comment]
For the release 0.19.0 - yes.

Additionally, we have to implement:

* file owner/group
* modification of creation/modification/access time
* processing subfolders
* filters (multi-file attributes)

Every item of the aforementioned list can be a separate ticket.
