### ISSUE TITLE
After renamig, put the cursor on the renamed file

### ISSUE THREAD

**Issue by corporateshark** [corporateshark/WalCommander#73]

**Comment by corporateshark** [comment]
@helgp Can we close this?

**Comment by helgp** [comment]
Yes, the bug is gone.

**Comment by belonesox** [comment]
I still see the bug in v0.20.0 (on our build of WCM Commander, https://abf.io/import/wcmcommander/blob/rosa2014.1/wcmcommander.spec ).

Can someone check that the bug is gone or  still exists?

**Comment by helgp** [comment]
@belonesox 

Please, prepare a reproducible test case.

**Comment by belonesox** [comment]
Sorry, suddenly the bug stop reproducing. If I encounter it next time, I will try to screencast and explore it.
